using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace Starlight.CodeGen.Component;

/// <summary>
/// Generates a <c>GeneratedModuleRegistration.Register(ModuleRegistry)</c> method for a component
/// assembly. Every type implementing <c>IModule</c> is registered with a per-player factory
/// (<c>(sp, p) =>; ActivatorUtilities.CreateInstance[TModule](sp, p)</c>), so a module's
/// constructor receives the session <c>IPlayer</c> plus any services resolved from DI; each
/// <c>[Opcode]</c>-annotated method on those modules is
/// registered as a handler keyed on its message type. Handlers are bound by analyzing their
/// parameters (the session <c>IPlayer</c> and/or the message) and their return shape (sync or
/// <c>Task</c>/<c>ValueTask</c>, returning nothing, a single message, or an enumerable of
/// messages); returned messages are sent back through <c>player.Send</c>. The dispatch key is the
/// message runtime type, never a cmd id, so component modules stay protocol-version agnostic.
/// </summary>
[Generator]
public sealed class ComponentModuleGenerator : IIncrementalGenerator
{
    private const string ModuleName = "Starlight.Game.Modules.IModule";
    private const string RegistryName = "Starlight.Game.Modules.ModuleRegistry";
    private const string PlayerName = "Starlight.Game.Player.IPlayer";
    private const string OpcodeAttributeName = "Starlight.Protocol.OpcodeAttribute";
    private const string MessageName = "Starlight.Protobuf.Core.IMessage";

    private static readonly SymbolDisplayFormat FullyQualified = SymbolDisplayFormat.FullyQualifiedFormat;

    private static readonly DiagnosticDescriptor UninferableMessage = new(
        "SLCMP001", "Cannot infer packet handler message type",
        "Packet handler '{0}' has no single message-typed parameter to infer the opcode from; declare exactly one message parameter or pass the type explicitly as [Opcode(typeof(...))]",
        "Starlight.Components", DiagnosticSeverity.Error, isEnabledByDefault: true);

    private static readonly DiagnosticDescriptor UnsupportedParameter = new(
        "SLCMP002", "Unsupported packet handler parameter",
        "Packet handler '{0}' parameter '{1}' has unsupported type '{2}'; allowed: IPlayer or a message type",
        "Starlight.Components", DiagnosticSeverity.Error, isEnabledByDefault: true);

    public void Initialize(IncrementalGeneratorInitializationContext context)
        => context.RegisterSourceOutput(context.CompilationProvider, Generate);

    private static void Generate(SourceProductionContext spc, Compilation compilation)
    {
        var moduleIface = compilation.GetTypeByMetadataName(ModuleName);
        var registry = compilation.GetTypeByMetadataName(RegistryName);
        var player = compilation.GetTypeByMetadataName(PlayerName);
        var opcodeAttr = compilation.GetTypeByMetadataName(OpcodeAttributeName);
        var iMessage = compilation.GetTypeByMetadataName(MessageName);

        // Without these the assembly doesn't reference the module runtime; nothing to do.
        if (moduleIface is null || registry is null || player is null || opcodeAttr is null || iMessage is null)
            return;

        var task1 = compilation.GetTypeByMetadataName("System.Threading.Tasks.Task`1");
        var valueTask1 = compilation.GetTypeByMetadataName("System.Threading.Tasks.ValueTask`1");
        var task = compilation.GetTypeByMetadataName("System.Threading.Tasks.Task");
        var valueTask = compilation.GetTypeByMetadataName("System.Threading.Tasks.ValueTask");

        var modules = new List<INamedTypeSymbol>();
        CollectModules(compilation.Assembly.GlobalNamespace, moduleIface, modules);

        if (modules.Count == 0)
            return;

        var sb = new StringBuilder();
        var ns = compilation.AssemblyName ?? "Starlight.Generated";

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine($"namespace {ns};");
        sb.AppendLine();
        var registryFq = registry.ToDisplayString(FullyQualified);

        // Derive a unique, chainable method name from the component assembly's last segment
        // (e.g. "Starlight.Game.Social" => "AddSocialComponent"), so several components can be
        // registered side by side without their extension methods colliding.
        var componentName = ns.Split('.').Last();
        var methodName = $"Add{componentName}Component";

        sb.AppendLine("/// <summary>Generated module registration for this component assembly.</summary>");
        sb.AppendLine("public static class GeneratedModuleRegistration");
        sb.AppendLine("{");

        sb.AppendLine(
            $"    /// <summary>Registers every <c>IModule</c> in the <c>{componentName}</c> component with <paramref name=\"registry\"/>, returning it for chaining.</summary>");
        sb.AppendLine($"    public static {registryFq} {methodName}(this {registryFq} registry)");
        sb.AppendLine("    {");

        foreach (var module in modules.OrderBy(m => m.ToDisplayString(FullyQualified), StringComparer.Ordinal))
        {
            var moduleFq = module.ToDisplayString(FullyQualified);

            sb.AppendLine(
                $"        registry.AddModule<{moduleFq}>(static (sp, p) => global::Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance<{moduleFq}>(sp, p));");

            foreach (var method in module.GetMembers().OfType<IMethodSymbol>())
            {
                var attribute = method.GetAttributes().FirstOrDefault(a =>
                    SymbolEqualityComparer.Default.Equals(a.AttributeClass, opcodeAttr));

                if (attribute is null)
                    continue;

                var messageType = ResolveMessageType(attribute, method, iMessage);

                if (messageType is null)
                {
                    spc.ReportDiagnostic(Diagnostic.Create(UninferableMessage,
                        method.Locations.FirstOrDefault(), method.Name));
                    continue;
                }

                EmitHandler(spc, sb, module, method, attribute, messageType, player, iMessage,
                    task1, valueTask1, task, valueTask);
            }
        }

        sb.AppendLine("        return registry;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        spc.AddSource("GeneratedModuleRegistration.g.cs", sb.ToString());
    }

    private static void EmitHandler(
        SourceProductionContext spc,
        StringBuilder sb,
        INamedTypeSymbol module,
        IMethodSymbol method,
        AttributeData opcode,
        INamedTypeSymbol messageType,
        INamedTypeSymbol player,
        INamedTypeSymbol iMessage,
        INamedTypeSymbol? task1,
        INamedTypeSymbol? valueTask1,
        INamedTypeSymbol? task,
        INamedTypeSymbol? valueTask
    )
    {
        var moduleFq = module.ToDisplayString(FullyQualified);
        var messageFq = messageType.ToDisplayString(FullyQualified);

        var args = new List<string>();
        var usesMessage = false;

        foreach (var parameter in method.Parameters)
        {
            if (IsAssignable(player, parameter.Type))
                args.Add("player");
            else if (IsAssignable(parameter.Type, iMessage))
            {
                args.Add("__msg");
                usesMessage = true;
            } else
            {
                spc.ReportDiagnostic(Diagnostic.Create(UnsupportedParameter,
                    parameter.Locations.FirstOrDefault(), method.Name, parameter.Name,
                    parameter.Type.ToDisplayString()));
                return;
            }
        }

        var ret = ClassifyReturn(method.ReturnType, iMessage, task1, valueTask1, task, valueTask);

        var priority = 0;

        foreach (var named in opcode.NamedArguments)
        {
            if (named.Key == "Priority" && named.Value.Value is int value)
                priority = value;
        }

        // Sending needs an async lambda too, or the next handler in the chain can publish first.
        var isAsync = ret.Awaitable || ret.Send != SendKind.None;
        var asyncMod = isAsync ? "async " : "";
        sb.AppendLine($"        registry.AddHandler<{moduleFq}, {messageFq}>({priority}, {asyncMod}static (module, player, message) =>");
        sb.AppendLine("        {");
        sb.AppendLine($"            var __m = ({moduleFq})module;");

        if (usesMessage)
            sb.AppendLine($"            var __msg = ({messageFq})message;");

        var invoke = $"__m.{method.Name}({string.Join(", ", args)})";
        var call = ret.Awaitable ? $"await {invoke}" : invoke;

        switch (ret.Send)
        {
            case SendKind.None:
                sb.AppendLine($"            {call};");
                break;
            case SendKind.Single:
                sb.AppendLine($"            var __result = {call};");
                sb.AppendLine("            if (__result is not null) await player.Send(__result);");
                break;
            case SendKind.Many:
                sb.AppendLine($"            var __results = {call};");
                sb.AppendLine("            if (__results is not null)");
                sb.AppendLine("                foreach (var __message in __results)");
                sb.AppendLine("                    if (__message is not null) await player.Send(__message);");
                break;
        }

        if (!isAsync)
        {
            sb.AppendLine("            return default;");
        }

        sb.AppendLine("        });");
    }

    private static INamedTypeSymbol? ResolveMessageType(
        AttributeData attribute,
        IMethodSymbol method,
        INamedTypeSymbol iMessage
    )
    {
        if (attribute.ConstructorArguments.Length > 0 &&
            attribute.ConstructorArguments[0].Value is INamedTypeSymbol explicitType)
            return explicitType;

        INamedTypeSymbol? inferred = null;

        foreach (var parameter in method.Parameters)
        {
            if (parameter.Type is not INamedTypeSymbol named ||
                SymbolEqualityComparer.Default.Equals(named, iMessage) ||
                !IsAssignable(named, iMessage))
                continue;

            if (inferred is not null)
                return null; // ambiguous

            inferred = named;
        }

        return inferred;
    }

    private static void CollectModules(INamespaceSymbol ns, INamedTypeSymbol moduleIface, List<INamedTypeSymbol> output)
    {
        foreach (var type in ns.GetTypeMembers())
        {
            CollectFromType(type, moduleIface, output);
        }

        foreach (var child in ns.GetNamespaceMembers())
        {
            CollectModules(child, moduleIface, output);
        }
    }

    private static void CollectFromType(INamedTypeSymbol type, INamedTypeSymbol moduleIface, List<INamedTypeSymbol> output)
    {
        if (type is { IsAbstract: false, TypeKind: TypeKind.Class } && IsAssignable(type, moduleIface))
            output.Add(type);

        foreach (var nested in type.GetTypeMembers())
        {
            CollectFromType(nested, moduleIface, output);
        }
    }

    private static ReturnInfo ClassifyReturn(
        ITypeSymbol returnType,
        INamedTypeSymbol iMessage,
        INamedTypeSymbol? task1,
        INamedTypeSymbol? valueTask1,
        INamedTypeSymbol? task,
        INamedTypeSymbol? valueTask
    )
    {
        var awaitable = false;
        var inner = returnType;

        if (returnType is INamedTypeSymbol named)
        {
            var definition = named.ConstructedFrom;

            if (SymbolEqualityComparer.Default.Equals(definition, task1) ||
                SymbolEqualityComparer.Default.Equals(definition, valueTask1))
            {
                awaitable = true;
                inner = named.TypeArguments[0];
            } else if (SymbolEqualityComparer.Default.Equals(named, task) ||
                       SymbolEqualityComparer.Default.Equals(named, valueTask))
            {
                return new ReturnInfo(awaitable: true, SendKind.None);
            }
        }

        if (inner.SpecialType == SpecialType.System_Void)
            return new ReturnInfo(awaitable, SendKind.None);

        var item = GetEnumerableItem(inner);

        if (item is not null && IsAssignable(item, iMessage))
            return new ReturnInfo(awaitable, SendKind.Many);

        if (IsAssignable(inner, iMessage))
            return new ReturnInfo(awaitable, SendKind.Single);

        return new ReturnInfo(awaitable, SendKind.None);
    }

    private static ITypeSymbol? GetEnumerableItem(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol { OriginalDefinition.SpecialType: SpecialType.System_Collections_Generic_IEnumerable_T } named)
            return named.TypeArguments[0];

        foreach (var iface in type.AllInterfaces)
        {
            if (iface.OriginalDefinition.SpecialType == SpecialType.System_Collections_Generic_IEnumerable_T)
                return iface.TypeArguments[0];
        }

        return null;
    }

    private static bool IsAssignable(ITypeSymbol source, ITypeSymbol destination)
    {
        if (SymbolEqualityComparer.Default.Equals(source, destination))
            return true;

        for (var baseType = source.BaseType; baseType is not null; baseType = baseType.BaseType)
            if (SymbolEqualityComparer.Default.Equals(baseType, destination))
                return true;

        foreach (var iface in source.AllInterfaces)
        {
            if (SymbolEqualityComparer.Default.Equals(iface, destination))
                return true;
        }

        return false;
    }
}

internal enum SendKind
{
    None,
    Single,
    Many
}

internal readonly struct ReturnInfo(bool awaitable, SendKind send)
{
    public bool Awaitable { get; } = awaitable;
    public SendKind Send { get; } = send;
}
