<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Starlight.Game.Social</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\Source\Starlight.Game\Starlight.Game.csproj" />
        <ProjectReference Include="..\Starlight.Game.Resources\Starlight.Game.Resources.csproj" />
        <ProjectReference Include="..\Starlight.Protocol\Starlight.Protocol.csproj" />
        <ProjectReference Include="..\Starlight.CodeGen.Component\Starlight.CodeGen.Component.csproj"
                          OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
    </ItemGroup>

</Project>
