using System.Text;
using Google.Protobuf.Reflection;

namespace Starlight.Protobuf.Compiler;

public sealed partial class ProtobufCompiler
{
    private static void EmitTopLevelEnum(StringBuilder sb, EnumDescriptorProto e)
    {
        sb.AppendLine($"public enum {CodeEmitter.StripPrefix(e.Name)}");
        sb.AppendLine("{");

        foreach (var v in e.Values)
        {
            sb.AppendLine($"    {v.Name} = {v.Number},");
        }
        sb.AppendLine("}");
        sb.AppendLine();
    }

    private static string Capitalize(string package) =>
        package.Length == 0 ? package : char.ToUpperInvariant(package[0]) + package.Substring(1);

    private static string Stem(string fileName)
    {
        var dot = fileName.LastIndexOf('.');
        return dot < 0 ? fileName : fileName.Substring(startIndex: 0, dot);
    }

    private static string Wrap(string ns, string body) => $"""
                                                           // <auto-generated/>
                                                           #nullable enable
                                                           namespace {ns};

                                                           {body}
                                                           """;
}
