syntax = "proto3";

package starlight.player;

option csharp_namespace = "Starlight.Rpc.Proto";

import "starlight.proto";

message NetPlayer {
  // The game ID. Pure number used across the game.
  uint32 uid = 1;
  // The account ID. Assigned by the SDK server.
  string account_id = 2;
  NetPlayerProfile profile = 3;
}

message NetPlayerProfile {
  string nickname = 1;
  string signature = 2;
  uint32 picture_id = 3;
  uint32 name_card_id = 4;
}

// --- MESSAGES START --- \\

// Path: Game Server -> DB Gate
// Subject: `game.player.fetch`
message FetchPlayerReq {
  // If one account can be on multiple regions,
  // we should only need to know what the account ID is.
  //
  // Each region can only have one player per account, and the
  // user connects to a specific region with a specific DB Gate,
  // so one account ID + one region -> one player.
  string account_uid = 1;

  // Used exclusively for first login scenarios.
  // If the player doesn't exist, their data will be created.
  optional bool create = 2;
}

// Path: DB Gate -> Game Server
// Subject: `game.player.fetch`
message FetchPlayerRsp {
  StarlightRetcode retcode = 1;
  optional NetPlayer player = 2;
}

// Sent as a metadata payload for informing the game server
// of the connecting player.
//
// Subject: <none>
message PlayerConnectNotify {
  uint32 uid = 1;
  string remote_addr = 2;
  uint32 remote_port = 3;
}
